#pragma once

const char* const sqlCreateTables =
"CREATE TABLE IF NOT EXISTS [metadata] (                                     \n"
"  [key] TEXT COLLATE NOCASE PRIMARY KEY NOT NULL,                           \n"
"  [value] TEXT DEFAULT NULL                                                 \n"
");                                                                          \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS [accounts] (                                     \n"
"    [account_id] INTEGER NOT NULL,                                          \n"
"    [name] TEXT COLLATE NOCASE NOT NULL,                                    \n"
"    [created_on] INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),          \n"
"    [usergroup] TEXT DEFAULT NULL,                                          \n"
"    [flags] INTEGER NOT NULL DEFAULT 0,                                     \n"
"    PRIMARY KEY ( [account_id] ),                                           \n"
"    UNIQUE ( [name] )                                                       \n"
");                                                                          \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS [sessions] (                                     \n"
"    [session_id] INTEGER NOT NULL,                                          \n"
"    [identifier] INTEGER NOT NULL,                                          \n"
"    [info] TEXT NOT NULL,                                                   \n"
"    [account_id] INTEGER DEFAULT NULL,                                      \n"
"    [temporary] INTEGER NOT NULL DEFAULT 1,                                 \n"
"    PRIMARY KEY ( [session_id] ),                                           \n"
"    UNIQUE ( [identifier] ),                                                \n"
"    FOREIGN KEY ( [account_id] )                                            \n"
"        REFERENCES accounts ( [account_id] )                                \n"
"        ON DELETE SET NULL                                                  \n"
");                                                                          \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS nicknames (                                      \n"
"    [ip_int] INTEGER,                                                       \n"
"    [name] TEXT,                                                            \n"
"    [duration] INTEGER,                                                     \n"
"    [cuid_hash2] TEXT                                                       \n"
");                                                                          \n"
"                                                                            \n"
"CREATE INDEX IF NOT EXISTS nicknames_ip_int_idx                             \n"
"ON nicknames ( ip_int );                                                    \n"
"                                                                            \n"
"CREATE INDEX IF NOT EXISTS nicknames_cuid_hash2_idx                         \n"
"ON nicknames ( cuid_hash2 );                                                \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS fastcapsV2 (                                     \n"
"    [fastcap_id] INTEGER PRIMARY KEY AUTOINCREMENT,                         \n"
"    [mapname] TEXT,                                                         \n"
"    [rank] INTEGER,                                                         \n"
"    [type] INTEGER,                                                         \n"
"    [player_name] TEXT,                                                     \n"
"    [player_ip_int] INTEGER,                                                \n"
"    [player_cuid_hash2] TEXT,                                               \n"
"    [capture_time] INTEGER,                                                 \n"
"    [whose_flag] INTEGER,                                                   \n"
"    [max_speed] INTEGER,                                                    \n"
"    [avg_speed] INTEGER,                                                    \n"
"    [date] INTEGER,                                                         \n"
"    [match_id] TEXT,                                                        \n"
"    [client_id] INTEGER,                                                    \n"
"    [pickup_time] INTEGER);                                                 \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS ip_whitelist (                                   \n"
"    [ip_int] INTEGER PRIMARY KEY,                                           \n"
"    [mask_int] INTEGER,                                                     \n"
"    [notes] TEXT);                                                          \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS ip_blacklist (                                   \n"
"    [ip_int] INTEGER PRIMARY KEY,                                           \n"
"    [mask_int] INTEGER,                                                     \n"
"    [notes] TEXT,                                                           \n"
"    [reason] TEXT,                                                          \n"
"    [banned_since] DATETIME,                                                \n"
"    [banned_until] DATETIME);                                               \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS pools (                                          \n"
"    [pool_id] INTEGER PRIMARY KEY AUTOINCREMENT,                            \n"
"    [short_name] TEXT,                                                      \n"
"    [long_name] TEXT );                                                     \n"
"                                                                            \n"
"CREATE TABLE IF NOT EXISTS pool_has_map (                                   \n"
"    [pool_id] INTEGER REFERENCES [pools]([pool_id]) ON DELETE RESTRICT,     \n"
"    [mapname] TEXT,                                                         \n"
"    [weight] INTEGER);                                                        ";
